version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  worker1:
    build: .
    depends_on:
      - redis

  worker2:
    build: .
    depends_on:
      - redis

  worker3:
    build: .
    depends_on:
      - redis

  task_trigger:
    build: .
    depends_on:
      - redis
    command: python sample.py
